default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: database_queries_development
  username: rubyuser
  password: newlife
  host: localhost
  port: 5432

test:
  <<: *default
  database: database_queries_test
  username: rubyuser
  password: newlife
  host: localhost
  port: 5432
